### ISSUE TITLE
Leia Backport Build: pvr.waipu did not match any of the supported addons.

### ISSUE THREAD

**Issue by KlausHans** [flubshi/pvr.waipu#101]
**Describe the bug / Beschreibe den Fehler**
Hi, i tried to build the leia backport for Linux (Libreelec on a htpc to be exact) because i did not find a build of this.
Instead of
```
git clone --branch master https://github.com/xbmc/xbmc.git
git clone --branch Matrix https://github.com/flubshi/pvr.waipu.git
```
i used
```
git clone --branch Leia https://github.com/xbmc/xbmc.git
git clone --branch Leia-Backported https://github.com/flubshi/pvr.waipu.git
```
Unfortunately cmake ends with 
```
CMake Error at CMakeLists.txt:441 (message):
  pvr.waipu did not match any of the supported addons.  A list of supported
  addons can be viewed by building the 'supported_addons' target.  Addon
  definitions are loaded from ADDONS_DEFINITION_DIR
  (/home/user/Dokumente/Waipu PVR/xbmc/cmake/addons/addons).
```
How can i solve this? Thanks.
I think this is maybe not a bug, more an issue of lacking documentation. ;)

**Comment by flubshi** [comment]
Please try this:

```
git clone --branch Leia https://github.com/xbmc/xbmc.git
mkdir -p xbmc/cmake/addons/addons/pvr.waipu/
echo "pvr.waipu https://github.com/flubshi/pvr.waipu Leia-Backported" > xbmc/cmake/addons/addons/pvr.waipu/pvr.waipu.txt
echo "all" > xbmc/cmake/addons/addons/pvr.waipu/platforms.txt

git clone --branch Leia-Backported https://github.com/flubshi/pvr.waipu.git
mkdir -p pvr.waipu/build && cd pvr.waipu/build

cmake -DADDONS_TO_BUILD=pvr.waipu -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons
make
```

It is described in Leia branch. Matrix is working without step 3 & 4, because pvr.waipu is official kodi addon since Matrix.

**Comment by KlausHans** [comment]
Thank you for the quick reply. Now i get
```
[ 12%] Performing configure step for 'rapidjson'
/bin/sh: 1: PKG_CONFIG_PATH=/home/user/Dokumente/Waipu PVR/pvr.waipu/build/build/depends/lib/pkgconfig: not found
make[2]: *** [CMakeFiles/rapidjson.dir/build.make:110: build/rapidjson/src/rapidjson-stamp/rapidjson-configure] Fehler 127
make[2]: Verzeichnis „/home/user/Dokumente/Waipu PVR/pvr.waipu/build“ wird verlassen
make[1]: *** [CMakeFiles/Makefile2:160: CMakeFiles/rapidjson.dir/all] Fehler 2
make[1]: Verzeichnis „/home/user/Dokumente/Waipu PVR/pvr.waipu/build“ wird verlassen
make: *** [Makefile:84: all] Fehler 2
```
if i invoke `make`.
Hm, maybe it is better if i switch to ubuntu and use matrix.
Edit: oh, just saw, that matrix isn't even released yet.

**Comment by daschaffert** [comment]
Hi, I used Ubuntu 18.04.5 LTS (Bionic Beaver) in a virtual machine to build a working plugin for libreelec 9.2.6 generic

**Comment by flubshi** [comment]
> ```
> [ 12%] Performing configure step for 'rapidjson'
> /bin/sh: 1: PKG_CONFIG_PATH=/home/user/Dokumente/Waipu PVR/pvr.waipu/build/build/depends/lib/pkgconfig: not found
> make[2]: *** [CMakeFiles/rapidjson.dir/build.make:110: build/rapidjson/src/rapidjson-stamp/rapidjson-configure] Fehler 127
> make[2]: Verzeichnis „/home/user/Dokumente/Waipu PVR/pvr.waipu/build“ wird verlassen
> make[1]: *** [CMakeFiles/Makefile2:160: CMakeFiles/rapidjson.dir/all] Fehler 2
> make[1]: Verzeichnis „/home/user/Dokumente/Waipu PVR/pvr.waipu/build“ wird verlassen
> make: *** [Makefile:84: all] Fehler 2
> ```
Maybe it is related to the space in folder name. Or you could try to install rapidjson-dev from you distributions repository.

**Comment by KlausHans** [comment]
Obviously it was indeed the space. It builds now. Thank you again.

**Comment by KlausHans** [comment]
OT: Puh, now i tried to install it, but the activation in Libreelec fails with:
```
2020-12-22 14:14:12.698 T:140674515158784   ERROR: Unable to load /storage/.kodi/addons/pvr.waipu/pvr.waipu.so.2.3.0, reason: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /storage/.kodi/addons/pvr.waipu/pvr.waipu.so.2.3.0)
2020-12-22 14:14:27.630 T:140674515158784   ERROR: UpdateAddons: Failed to create add-on waipu.tv PVR Client, status = 5

```
Someone already posted similar problem here https://www.kodinerds.net/index.php/Thread/64613-Release-PVR-Plugin-Waipu-tv-f%C3%BCr-Kodi-19/?postID=580256#post580256 unfortunately no solution.
