### ISSUE TITLE
Mindestens eine Datei konnte nicht abgespielt werden. Für mehr Details Logdatei einsehen

### ISSUE THREAD

**Issue by volker-raschek** [flubshi/pvr.waipu#123]
**Describe the bug / Beschreibe den Fehler**

Erhalte die Fehlermeldung `Mindestens eine Datei konnte nicht abgespielt werden. Für mehr Details Logdatei einsehen` allen dritten Programmen wie RTL, Pro7, Vox ect. Die öffentlichen wie ARD und ZDF einwandfrei. Aus dem log konnte ich selber nichts entnehmen.

[IMG_20210615_200018](https://user-images.githubusercontent.com/18311012/122101670-e1ecea80-ce14-11eb-8c74-69b490b010a7.jpg)

**Environment / Umgebung:**

 - Kodi version: 19
 - OS: LibreElec
 - pvr.waipu version: 2.8.4.1
 - inputstream.adaptive version: 0.5.5+matrix.1

**kodi logs**

[kodi.waipu.log](https://github.com/flubshi/pvr.waipu/files/6657691/kodi.waipu.log)
[kodi_crash.log](https://github.com/flubshi/pvr.waipu/files/6657693/kodi_crash.log)

**Comment by flubshi** [comment]
Wenn die Öffentlichen funktionieren und die Privaten nicht, ist das in der Regel ein Problem von Widevine / inputstream.adaptive.

Ende Mai gab es eine Widevine Umstellung, diese erfordert ein aktuelles LibreELEC und eine aktuelle Widevine Version. Zudem ist ggf. eine Config-Anpassung notwendig. Siehe: https://libreelec.tv/2021/05/le-9-2-7-10b4-fix-widevine/

- Welche LibreELEC Version verwendest Du?
- ist ein aktuelles widevine über das inputstream-helper addon installiert?

**Comment by volker-raschek** [comment]
Nabend @flubshi,

> - Welche LibreELEC Version verwendest Du? 

ich habe LibreELEC Version 9.95.4 installiert.

> - ist ein aktuelles widevine über das inputstream-helper addon installiert?

Das ist eine gute Frage. Ich habe in den Einstellungen keine Versionsangabe finden können. 

> Zudem ist ggf. eine Config-Anpassung notwendig.

Ich habe die config angepasst und den PI neu gestartet. Seit dem funktionieren die privaten Sender wieder. Vielen Dank für den Tipp.

**Comment by flubshi** [comment]
> Ich habe die config angepasst und den PI neu gestartet. Seit dem funktionieren die privaten Sender wieder. Vielen Dank für den Tipp.

Freut mich zu hören. Ich denke damit kann das Issue geschlossen werden :)

**Comment by volker-raschek** [comment]
Nabend @flubshi, 
das Problem beim streamen der privaten Sender tritt erneut auf. Ich erhalte wieder die Fehlermeldung `Mindestens eine Datei konnte nicht abgespielt werden. Für mehr Details Logdatei einsehen`. 

Ich habe versucht die kürzlich veröffentlichte Version `2.9.3` über das offizielle LibreElec repository zu installieren, um eventuelle behandelte Fehler ausschließend zu können. Allerdings findet kodi die Version nicht. Die letzte verfügbare Version ist `2.9.0-1`. 

Hier eine Zusammenfassung der Versionen:

- Kodi version: 19
- OS: LibreElec 9.95.1
- pvr.waipu version: 2.9.0-1
- inputstream.adaptive version: 0.5.7+matrix.1

1. Irgend eine Idee warum die Version nicht verfügbar ist?
2. Trotz Anpassung der config, wie auf https://libreelec.tv/2021/05/le-9-2-7-10b4-fix-widevine/ beschrieben, funktioniert das steamen aktuell nicht

**Comment by flubshi** [comment]
> 1. Irgend eine Idee warum die Version nicht verfügbar ist?

Die neue Version wurde bereits seitens LibreELEC übernommen und kompiliert. Allerdings funktioniert die Aktualisierung des Repositories wohl manuell und der Schritt ist vermutlich nicht passiert. Ehrlicherweise etwas unverständlich weshalb das nicht automatisiert passiert...

> 2. Trotz Anpassung der config, wie auf https://libreelec.tv/2021/05/le-9-2-7-10b4-fix-widevine/ beschrieben, funktioniert das steamen aktuell nicht

Ohne Debug-Log kann ich nicht sagen woran es liegt. Bei mir funktioniert es mit exakt der LibreELEC und pvr.waipu Version, also ist es kein grunsätzliches Problem.

**Comment by volker-raschek** [comment]
Hi @flubshi,

> Ohne Debug-Log kann ich nicht sagen woran es liegt. Bei mir funktioniert es mit exakt der LibreELEC und pvr.waipu Version, also ist es kein grunsätzliches Problem. 

hier die log files. Falls du noch andere Informationen benötigst, gib mir Bescheid.

http://ix.io/3sMk
