### ISSUE TITLE
Can only install Version 19.0.1

### ISSUE THREAD

**Issue by Smoker2604** [flubshi/pvr.waipu#180]
**Describe the bug / Beschreibe den Fehler**
Feel free to write in english or in german.

**Environment / Umgebung:**
Hardware: Raspberry Pi 4 mit 8GB
 - Kodi version: 19.3
 - OS:
          PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
          NAME="Raspbian GNU/Linux"
          VERSION_ID="11"
          VERSION="11 (bullseye)"
 - pvr.waipu version 19.0.1

Ich kann leider nur die Version 19.0.1 vom addon installieren. 
Leider habe ich unter Repe keinen eintrag PVR Clients und muss es manuell installieren.
Ich habe das addon wie folgt installiert: < apt-get install pvr.waipu >.
Es wird aber leider die Version 19.0.1 installiert und nciht die aktuelle Version 20.3.0.

Wenn ich Wie auf GitHub beschrieben die Build instructions ausführe, lauft alles durch, aber es wird mir kein Addon angezeigt.

Funktioniert die Version 20.3.0 noch nicht unter Kodi 19 oder mache ich was falsch?

Liebe Grüße 
Tobias

**Comment by flubshi** [comment]
Hallo Tobias,

die erste Stelle der Addon-Version gibt an, mit welcher Kodi-Version das Plugin kompatibel ist. Für Kodi 19 (Matrix) ist die aktuelle Version 19.1.1-Matrix, für die Enwicklungsversion (Nexus) die Addon Version 20.3.0-Nexus.

Wann/wie das Debian/Raspian Repo aktualisiert wird, kann ich dir leider nicht sagen. Das liegt in der Verantwortung der Distribution/desRepos.
