### ISSUE TITLE
No Waipu.tv Addon Available

### ISSUE THREAD

**Issue by Tibercad** [flubshi/pvr.waipu#203]
Hello,

i use a Android TV Box (Android 11). It is a RKMC client preinstalled. When i go to Playstore and search for Kodi. there stands Kodi is already installed. But when i go in the Menu i dondt find the standard Kodi Repository like shown in the tutorial for installing Waipu.tv.

Is there an option to install the Addon manually as a zip file?

**Comment by flubshi** [comment]
Not sure what RKMC is. But imI guess ZIP file can be installed via menu.
