### ISSUE TITLE
Aufnahmen nicht sichtbar

### ISSUE THREAD

**Issue by dneuhaeuser** [flubshi/pvr.waipu#213]
**Describe the bug / Beschreibe den Fehler**
vorhandene Aufnahmen werden nicht angezeigt
Infos zur momentanen/nächsten Aufnahme und Timer werden angezeigt
Unter Aufnahmen aber immer 0 Elemente

**Environment / Umgebung:**
 - Kodi version: 19.5
 - OS: Android 9
 - pvr.waipu version 19.3.1
 - inputstream.adaptive version 19.0.7

**Comment by flubshi** [comment]
@dneuhaeuser vielen Dank für dein Issue.
Ich kann es leider nicht reproduzieren. Besteht das Problem noch?

**Comment by dneuhaeuser** [comment]
seit dem Update auf Kodi 20 und der Aktualisierung des waipu Plugins ist das Problem nicht mehr aufgetreten.
