### ISSUE TITLE
Please branch from "Nexus" to "Omega"

### ISSUE THREAD

**Issue by phunkyfish** [flubshi/pvr.waipu#217]
The build pipelines are setup, once you are done let me know and we can re-enable this add-on for Omega (Kodi 21) builds

**Comment by flubshi** [comment]
Thanks for the hint @phunkyfish - branch for Omega is created.

**Comment by phunkyfish** [comment]
PR Created: https://github.com/xbmc/repo-binary-addons/pull/159

**Comment by flubshi** [comment]
I was faster ;)

**Comment by phunkyfish** [comment]
😃
