### ISSUE TITLE
waipu tv auf Fire TV Cube V1 und Kodi 19.4

### ISSUE THREAD

**Issue by Nachtfalke49** [flubshi/pvr.waipu#242]
Hallo,

ich habe den Fire TV Cube V1 und Kodi 19.4 drauf laufen. Ich suche nun nach einer Kabel TV Alternative. Ich habe mich bei waipu tv angemeldet und einen Testmonat für das Comfort Paket abegeschlossen. Bei waipu tv habe ich meine Kanäle sortiert und im Kodi den pvr waipu tv eingerichtet. Es funktioniert soweit alles. Leider nur in SD und nicht in HD. Ich habe davon gelesen, dass es was mit widevine DRM zu tun haben könnte. Bekomme ich irgendwie HD mit meiner Kombination zum Laufen?

Gruß

Andi

**Comment by flubshi** [comment]
Hi Andi,
für die DRM Kanäle wird Widevine benötigt, Größtenteils sollte das Abspielen der Waipu Kanäle auch mit Kodi und dem Waipu PVR Addon möglich sein.
Kann es sein, dass die von dir gewählten Kanäle nicht im Comfort Paket in HD enthalten sind?
https://www.waipu.tv/pakete-im-vergleich/
