### ISSUE TITLE
Lädt nur und kann keine liste erstellen 

### ISSUE THREAD

**Issue by Bambam11699** [flubshi/pvr.waipu#258]
**Describe the bug / Beschreibe den Fehler**
Nach starten des Addons kommt die meldung "PVR Manager wird gestartet" und er bleibt bei 0 % stehen

**Environment / Umgebung:**
 - Kodi version: 20
 - OS: Windows
 - pvr.waipu version 20.10.1
 - inputstream.adaptive version 20.3.12

![waipukodi](https://github.com/flubshi/pvr.waipu/assets/84667415/984d0443-a5b6-4eae-99c0-589b8e6b17e0)

**Comment by flubshi** [comment]
Welche Authentifizierung/Provider wurde in den Einstellungen gewählt?
Wurde die Authentifizierung durchgeführt?
Bringt ein Neustart von Kodi Abhilfe?

**Comment by Bambam11699** [comment]
Ich habe das Problem gefunden, der Fehler lag bei mir. Ich habe die daten des Amazon Logins genommen. Danke trotzdem.
