### ISSUE TITLE
Settings Screen suddenly blank

### ISSUE THREAD

**Issue by frostybiscuit** [flubshi/pvr.waipu#267]
**Describe the bug / Beschreibe den Fehler**
Waipu.tv client fails to load all of a sudden (worked fine the last few days) with an "authorisation failed" message. Everything worked fine today in the morning and now it suddenly won't show me any settings in the addon configuration screen.
I also have the Zattoo client running next to it, which has no issues.
I haven't changed anything within Kodi lately.
I already tried clearing the cache in Kodi, fully restarting the TV, reinstalling the addon, but all to no avail.

**Environment / Umgebung:**
 - Kodi version: 20
 - OS: Google TV 10.0
 - pvr.waipu version 20.10.2
 - inputstream.adaptive version 0.5.5

**Comment by flubshi** [comment]
Which authentication provider/Anbieter are you using? If you are using Waipu.tv (Credentials/Zugangsdaten), please switch to Waipu.tv (Device Authentication/Geräteanmeldung)

If you already use "Geräteanmeldung", please provide a debug log.

**Comment by frostybiscuit** [comment]
I was using the device authentication and it was working fine for more than a week, but like I said, all of a sudden the addon settings screen is empty. I tried clearing the cache, but other than losing my settings, nothing happened.

![IMG_20231109_222135](https://github.com/flubshi/pvr.waipu/assets/128132341/36b5b339-8548-48f1-8452-0329c186b6dd)

**Comment by flubshi** [comment]
In your screenshot, the headline says "Pluto.tv" but the Icon on the bottom left is waipu. Something seems broken there.

**Comment by frostybiscuit** [comment]
Yup, you're right.. So now to figure out why 🥲
Thanks for your time tho, highly appreciated 🙏

**Comment by frostybiscuit** [comment]
I've uninstalled the addon, fully turned off the TV, then reinstalled the addon again and it works now.
Definitely wasn't related to the addon itself, but probably some issue with Kodi itself.
Again, thank you for your time!
