### ISSUE TITLE
Bild bleibt beim Umschalten stehen

### ISSUE THREAD

**Issue by northstarex** [flubshi/pvr.waipu#275]
Moin

Ich habe einen neuen Win10 Rechner mit aktuellen Kodi und Waipu Plugin installiert. Immer wenn wir bei einigen Sendern z. B. von Pro7 auf RTL umschalten, dann bleibt nach dem Umschalten das Bild von Pro7 stehen, nur der Ton von RTL ist zu hören. Gibt es da ein Fix, oder habe ich da nicht beachtet bzw. nicht richtig eingestellt.

bis denne...
    North

**Comment by flubshi** [comment]
Hi North,
ohne weitere Details ist das schwierig zu sagen. Welche Version verwendest Du?
Klappt es, wenn Du direkt nach dem Starten des Streams ein wenig zurückspulst?

**Comment by flubshi** [comment]
@northstarex Läuft das Umschalten mittlerweile bei dir? Da ich es nicht für ein Addon Problem halte, sonder es vermutlich mit Kodi selbst zu tun hat, schließe ich dieses Ticket.

**Comment by northstarex** [comment]
@flubshi 
Moin,
ich habe eben gesehen, dass du das Plugin gepudatet hast. Das "zurück-spulen" innerhalb des Buffers geht jetzt überall, also bei jeden Sender. Sehr schön :)
Das mit Umschaltproblem liegt an dem einen Rechner hier. Irgendeine Komponente, die im Datenbus hängt, ist defekt. Ich habe hier auch diverse Abstürze mit der Kiste. Ein anderer Rechner läuft mit dem WaipuAddon ohne diese Probleme. Nur gibt es dort mal einen Kodi-Absturz, wenn man zu schnell zappt. Aber das liegt wohl am Kodi selbst. Das neuste Kodi hat da wohl wieder mal ein Codec Problem, wenn das überhaupt ein Problem ist.
Aber danke, dass du an meinen Post hier gedacht hast.

bis denne...
    North (www.norths.de)
