### ISSUE TITLE
compiling a version for batocera

### ISSUE THREAD

**Issue by goofy84** [flubshi/pvr.waipu#277]
Hello could you please compile a version for batocera? This is only working solution: plugin.video.waipu.tv-0.10.4-Matrix.zip. Is it possible to see the channels under TV and not under addons waipuTV. Batocera is a buildroot version, so there are PVR plugins in the repo.

**Comment by flubshi** [comment]
As far as I can see, pvr.waipu should be available in batocera:
https://github.com/batocera-linux/buildroot/tree/br2-external/package/kodi-pvr-waipu

**Comment by goofy84** [comment]
Thanks flubshi, but when i try to install the provided zip, there pops up an error message failed to install add-on from zip file Installing the add-on from zip failed du to an invalid structure. I am on batocera version 39c 2024/02/27 on an intel nuc 12 x86_64.
![PXL_20240302_130452268 MV](https://github.com/flubshi/pvr.waipu/assets/44529820/fc9a6342-a804-4e41-9330-99919d9b4d5e)

**Comment by goofy84** [comment]
![kodi version](https://github.com/flubshi/pvr.waipu/assets/44529820/e0703412-f47e-42e0-9e07-511d05fefc1d)

**Comment by flubshi** [comment]
Please ask the batocera team for help - I have no idea how to help you.

**Comment by flubshi** [comment]
I hope you got it work or contacted the batocera team. Since I have no knowledge to help you, I have closed this ticket.

**Comment by EinFreierUser** [comment]
The problem with batocera kodi is the missing inputstream adaptive and widevine. I also don't have a solution for that, but as a workaround: use the flatpak tool in batocera and install kodi from there. it appears in ports menu after installation and the version is much more up to date and allows using inputstream adaptive and widevine.
