### ISSUE TITLE
DAZN Kanäle laufen bei pvr,plutotv nicht

### ISSUE THREAD

**Issue by LeimertPark** [flubshi/pvr.waipu#283]
Hallo flubshi,

leider gibt es bei pvr.plutotv keinen "Issue" Reiter wo man Fehler melden kann,deshalb muß ich es hierüber machen!

Seit einigen Wochen laufen die DAZN Sender von Pluto im pvr.pluto nicht mehr.Im Kodi kommt der Hinweis:
Allgemeiner Wiedergabefehler.Bitte im Protokoll nachschauen!Benutzte Nexus 20
Aber auch im auf meinem Omega am PC gibt Kodi diesselbe Meldung!

Könntest du mal nachschauen?

Vielen Dank!

**Comment by ksooo** [comment]
> leider gibt es bei pvr.plutotv keinen "Issue" Reiter

Stimmt ja gar nicht. Guck mal genau hin....  Nee, Scherz beiseite, der fehlte tatsächlich. Habe ich gerade aktiviert. ;-)

**Comment by LeimertPark** [comment]
Ich sehe keinen!

**Comment by ksooo** [comment]
Dann brauchst du eine Brille (oder einen browser refresh). 

https://github.com/kodi-pvr/pvr.plutotv
https://github.com/kodi-pvr/pvr.plutotv/issues

**Comment by LeimertPark** [comment]
Danke!Gut,ich habe bei dem Entwickler flushbi geschaut!

**Comment by flubshi** [comment]
Das offizielle Repo ist zu kodi-pvr "umgezogen" (und nicht mehr bei mir), nachdem ich nicht mehr die Zeit hatte mich um die Weiterentwicklung zu kümmern und ksooo das freundlicherweise übernommen hat. Von der Expertise ist das Plugin auch bei ksooo wesentlich besser aufgehoben ;)
Ich denke das TIcket hier kann zu.
