### ISSUE TITLE
Proxy settings used only partially

### ISSUE THREAD

**Issue by cassi73** [flubshi/pvr.waipu#284]
**Describe the bug / Beschreibe den Fehler**
In my setup a need to connect to a proxy. Proxy settings are configured in Kodi, on the Android WIFI connection and via "http_proxy" and "global_http_proxy_host/port" ADB settings.

The sender list and EPG are working fine, connections are made through the proxy.
However, playing a stream fails because a few connections are made directly ignoring the proxy settings.

The connections which are missing the proxy settings target to e-f1-011-v4.wpstr.tv and e-f2-011-v4.wpstr.tv.

I tried it with Kodi on Linux and when I set additionally the "https_proxy" environment variable, the stream starts. However, on Android there is no way to set environment variables for apps.

**Environment / Umgebung:**
 - Kodi version: 20.4
 - OS: Android TV
 - pvr.waipu version 20.11.0
 - inputstream.adaptive version 20.3.17

**Comment by flubshi** [comment]
We have no control of how the stream is handled after handover to inputstream.adaptive. Without deeper inspection I would assume that inputstream.adaptive does not respect proxy settings.

**Comment by cassi73** [comment]
Ok. I didn't find relevant log entries neither in logcat nor in Kodi's log. Only saw those connection attempts in the firewall logs.
I noticed after enabling inputstream.ffmpegdirect, the stream worked (this addon has its own proxy settings).
But only for the public services, private stations failed with messages "no hardware decrypter found" or so.

Anyway, if it is a inputstream.adaptive issue, we can close this one.
