### ISSUE TITLE
Stream abbruchNach update auf Kodi omega

### ISSUE THREAD

**Issue by Ciencielos** [flubshi/pvr.waipu#285]
Nach dem update auf Kodi 21 Omega mit client waipu.tv PVR Client 21.5.0 crashen sämtliche live tv streams nach ca 10 Sekunden, ich habe parallel eine Kodifork 20.2  laufen, da funktioniert alles einwandfrei, habe auch schon das Skin auf estuary standard gesetzt, und auch von Androidbox auf Firetv gewechselt , gleiches Problem, ist diesbezüglich schon etwas bekannt?. oder kommt da noch ein Fix

**Comment by flubshi** [comment]
Auf welchem Gerät hast Du Kodi und das PVR Addon installiert?
Welche Version von inputstream.adaptive ist installiert?

Kannst Du bitte probieren in den Addon Einstellungen unter Streaming -> Protokoll auf MPEG_DASH umzustellen?

**Comment by Ciencielos** [comment]
Danke Dir, das Streamingprotokoll war auf Auto, habe es jetzt auf MPEG_DASH umgestellt und läuft einwandfrei

**Comment by martin3000** [comment]
Kann man vielleicht MPEG_DASH als default nehmen? Ich habe 2 Wochen gesucht bis ich hier die Lösung gefunden habe.

**Comment by flubshi** [comment]
> Kann man vielleicht MPEG_DASH als default nehmen? Ich habe 2 Wochen gesucht bis ich hier die Lösung gefunden habe.

In der aktuellen Version von pvr.waipu laufen bei mir die Streams in den Default Einstellungen. @martin3000 kannst Du bitte schreiben, mit welcher Version von inputstream.adaptive und pvr.waipu Du das Problem hast?

**Comment by martin3000** [comment]
> kannst Du bitte schreiben, mit welcher Version von inputstream.adaptive und pvr.waipu Du das Problem hast?

Kodi 21.1 on Linux, Waipu 21.8.6, ISH 0.6.1+matrix.1, ISA 21.5.2

**Comment by flubshi** [comment]
Ich habe dieselbe Kombination mit Abweichung ISA 21.5.4 getestet. 

[Changelog ISA](https://github.com/xbmc/inputstream.adaptive/releases):
- 21.5.3: [HLS] Fix non-stop playback problem when the decrypter is not initialised for some problem

Kannst Du bitte nochmal mit ISA 21.5.3 oder besser 21.5.4 ausprobieren? Wobei die Beschreibung nicht auf den Problem hindeutet :thinking:

**Comment by martin3000** [comment]
> Kannst Du bitte nochmal mit ISA 21.5.3 oder besser 21.5.4 ausprobieren?

Ich glaube das geht nicht, ich benutze gerade das flathub Paket.
