### ISSUE TITLE
New channel (Disney) are not showing in Pvr TV list

### ISSUE THREAD

**Issue by Gghuzr** [flubshi/pvr.waipu#291]
Due to the new 3 channel update from Waiputv channel list is incomplete. Need a fix to show up also the channel from the Disney deal

**Environment / Umgebung:**
 - Kodi version: [e.g. 18 or 19] 21 +20
 - OS: [e.g. LibreELEC, OSMC, Android TV] -;all effected
 - pvr.waipu version [latest]
 - inputstream.adaptive version [latest]

**Comment by flubshi** [comment]
The latest update for Nexus and Omega should fix the issue. The previously used API does not provide these channels, thus we had to change the API. With the update, the channels should be available and playable in Kodi, but the EPG might not work for all new channels. The update should be available next days in the Addon repositories.
