### ISSUE TITLE
EPG Indikatoren fehlen (Geplante Aufnahme zb)

### ISSUE THREAD

**Issue by Arokhaerr** [flubshi/pvr.waipu#299]
**Describe the bug / Beschreibe den Fehler**
Feel free to write in english or in german.
Seit Version 21.6.0.1 unter LibreElec fehlen beim EPG diese kleinen Symbole die zeigen ob man eine geplante Aufnahme hat. Ich bin zurück auf Version 21.5.1.2 und die Symbole sind wieder da. Gabs dazwischen einen Api Wechsel? Ich hab da was bezüglich Disney Channel mitbekommen von vor 4 Tagen in einer issue. Wäre es möglich Die Icons im EPG zurück zu bekommen damit man einfach sehen kann ob die Aufnahme schon geplant ist?

Danke im Voraus ;)

**Environment / Umgebung:**
 - Kodi version: [e.g. 18 or 19]
 - OS: [e.g. LibreELEC, OSMC, Android TV]
 - pvr.waipu version [e.g. 1.3.2]
 - inputstream.adaptive version [e.g. 0.5.2]
LibreElec 12 Omega auf einem Raspberry Pi 4b

**Comment by flubshi** [comment]
Korrekt analysiert: Es hat mit einem Wechsel der API für die Sender zu tun. Die neue API schreibt die Sendernamen klein, z.B. "zdf", währen die alte API "ZDF" verwendet. Da wir aktuell unterschiedliche APIs verwenden, habe ich einen Workaround implementiert.
