### ISSUE TITLE
Sound "leiert"

### ISSUE THREAD

**Issue by EinFreierUser** [flubshi/pvr.waipu#353]
Hey, ich habe das Problem, dass der Sound bei mir "leiert" und weiß auch nicht mehr, welches Stellrad ich bewegen soll, um das Problem zu lösen. Ab und an hab ich auch ein ganz leichtes "stottern" im Sound drin. Bild läuft flüssig. Mit anderen Addons gibt es auch keine Probleme beim Abspielen. Für einen Rat wäre ich sehr dankbar. 

**Environment / Umgebung:**
 - Kodi version: 21.1
 - OS: flatpak
 - pvr.waipu version 21.8.6
 - inputstream.adaptive version 21.5.2

**Comment by flubshi** [comment]
Schwierig da eine Diagnose zustellen. Ich denke, dass das PVR Addon da eher unschuldig ist. Ich würde mal probieren, wie es mit HLS vs MPEG_DASH aussieht, ob das einen Unterschied macht. Ansonsten ggf. anhand der Audiospuren, sofern unterschiedliche verfügbar.

**Comment by martin3000** [comment]
Habe ich auch, bei Musik ist es ganz schrecklich. In den letzten Tage war es aber wieder besser.

**Comment by flubshi** [comment]
Da ihr beide flatpak nutzt, würde ich es darauf schieben. Dazu gibt es bei Kodi und flathub auch Tickets. Laut den Tickets sollte es aber in Kodi 21.1 gefixt worden sein.

Aus meiner Sicht es kein Problem das wir in pvr.waipu haben bzw. in dem Plugin lösen können. Daher schließe ich das Addon.

Ich denke, dass ihr bei Kodi oder flathub eher Hilfe bekommen könnt:
- https://github.com/flathub/tv.kodi.Kodi/issues
- https://github.com/xbmc/xbmc/issues

**Comment by martin3000** [comment]
Es leiert aber nicht bei Youtube-Videos oder TVHeadend-Aufnahmen.....
