### ISSUE TITLE
Allgemeiner Fehler bei der Wiedergabe von privaten Sendern: RTL, VOX, Pro7 ect

### ISSUE THREAD

**Issue by volker-raschek** [flubshi/pvr.waipu#361]
## Problembeschreibung 

Beim aufrufen von privaten Sender wie beispielsweise RTL, VOX oder Pro7 erhalte ich die folgende Fehlermeldung: `Wiedergabe nicht Möglich: Allgemeiner Fehler bei der Wiedergabe. Für mehr Informationen Protokoll einsehen.` 

## Logs 

Ich habe per Strg + Shift + d das debug logging aktiviert und den Fehler reproduziert. Ich hoffe aus dem Anhang können notwenige Logs zur Fehleranalyse entnommen werden. Gerne stelle ich auch nochmal Logs bereit, sollten diese nicht die gewünschten Einträge enthalten.

[kodi.log](https://github.com/user-attachments/files/17757436/kodi.log)

## Metainformationen

**Environment / Umgebung:**
 - Kodi version: 21.1
 - OS:  LibreELEC
 - pvr.waipu version: 21.8.7.1
 - inputstream.adaptive version: 21.5.6.1

**Comment by flubshi** [comment]
> AddOnLog: inputstream.adaptive: Unable to load widevine shared library (/storage/.kodi/cdm/libwidevinecdm.so)

Bitte widevine über die Einstellungen/das inputstreamhelper Addon installieren.
