### ISSUE TITLE
Stuck on PVR manager is starting up

### ISSUE THREAD

**Issue by timosturm** [flubshi/pvr.waipu#362]
When accessing the TV tab in Kodi it is stuck on the message "PVR manager is starting up".

I have a clean install of OSMC; I activated the plugin waipu.tv PVR client and it is configured with credentials that I double checked. The plugin is enabled; but when checking under Settings -> TV & Radio -> General -> PVR clients, nothing is shown (should it be?).
OSMC is running on a raspberry pi, connected via WiFi.

 - Kodi version: 21.1
 - OS: OSMC 2024.10-1
 - pvr.waipu version: 21.8.6
 - inputstream.adaptive version 21.5.4
 
I have added the debug log after a restart and accessing the TV tab:
[kodi.log](https://github.com/user-attachments/files/17820787/kodi.log)
The plugin seems to fail at login.

**Comment by flubshi** [comment]
The credentials authentication is legacy authentication mode. I recommend to switch to device authentication.

Please switch to device authentication in Kodi. When a 6-Letter Code is shown, please use your mobile phone or notebook and open https://waipu.tv/anmelden in a web browser. Please enter the 6 letter code and confirm the device authentication.

I hope this fixes your issue. Feel free to report.

**Comment by timosturm** [comment]
Yes, it does indeed fix the issue :); thank you very much.
