### ISSUE TITLE
Pre-Compiled binaries for amd64/arm64

### ISSUE THREAD

**Issue by c4tz** [flubshi/pvr.waipu#37]
Hey there,

great work so far! I tried this addon yesterday and everything worked flawlessly.

I would like to package this addon for Arch Linux (like [pvr.iptvsimple](https://aur.archlinux.org/packages/kodi-addon-pvr-iptvsimple/)  e.g.). As I use Kodi on Arch Linux with a Raspberry as well as a self-built NAS (standard amd64), I'd need both architectures.

Is there any chance you could include binaries for them in your next releases (Leia and Matrix)? I saw the links/attachments on kodinerds, but for stability I'd prefer Jenkins, as you do it already for the other zip files.

I could also create git-packages (like [this one](https://aur.archlinux.org/packages/kodi-addon-pvr-iptvsimple-git/)) , but those are usually pretty slow to install on a Raspberry, as they need to be compiled every time ;)

**Comment by flubshi** [comment]
Hi c4tz,

thanks for your positive feedback! I am using Arch Linux as well and already thought about packaging pvr.waipu. If you have any experience, maybe we can work together.

I prefer automated packaging and building(e.g. by Jenkins) over manual updates. But the Kodi Jenkins I used to link pre-compiled zip-files is managed by team Kodi. Other pvr plugins, like pvr.iptvsimple are also not compiled by their Jenkins. Maybe we can ask for amd64 or arm64 builds.

Apart from prebuilt, I think a faster solution might be to provide an aur package that is compiled on the device. On my rpi it takes 10 (?) minutes to compile it. As this plugin has the most basic features implemented, it might be sufficient to update it when needed or a user is interested in new features.

Anyway, if you are interested to maintain the Arch package, I will support you. If changes to this Github Repo are required, feel free to open a PR or tell me what is needed.

**Comment by c4tz** [comment]
I don't have much experience other than creating a single AUR package before. But that one wasn't very hard to create, so I think we should be able to do this together ;)

Oh okay, I didn't notice it was built in Team Kodi's Jenkins. You're right, maybe we should just make a git-package and compile on install, if that is a faster and more simple way to get things done than asking them to do it for us.

I just noticed one problem: I didn't have inputstream installed on my rpi + NAS and couldn't find it in the official Kodi repo, somehow. On the NAS with amd64 architecture, that's fine because [there is a package for it](https://www.archlinux.org/packages/community/x86_64/kodi-addon-inputstream-adaptive/), but this is not available for arm7h. So I am currently not sure on how to get the inputstream(helper) addon working on Arch Linux ARM :/

We might have to package it separately. The smartest way should be just providing `script.module.inputstreamhelper` as a package, because that one doesn't need to be compiled and thus is independent of the architecture. What do you think about that?

**Comment by flubshi** [comment]
> On the NAS with amd64 architecture, that's fine because there is a package for it, but this is not available for arm7h

I think, there is an [AUR package](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=inputstream-adaptive) you can use on arm7h.

> The smartest way should be just providing script.module.inputstreamhelper as a package, because that one doesn't need to be compiled and thus is independent of the architecture.

`script.module.inputstreamhelper` and `inputstream.adaptive` are different plugins, we need both. Our pvr.waipu grabs the stream and DRM License information from the waipu API. This informtion is passed to `inputstream.adaptive` which prepares the playback. The playback/decoding of DRM is handled by widevine. Widevine is not shipped with Kodi, it is a blob that has to be grabbed (due to the license) from google. That's what  `script.module.inputstreamhelper`  is for: It checks if widevine is available and downloads it for your platform.

**Comment by c4tz** [comment]
> I think, there is an AUR package you can use on arm7h.

I already tried to install both of them yesterday. The problem is that `kodi-rpb` would be replaced by `kodi-devel`, which in turn has to be compiled for arm7h first. After about 6h of compiling and about 25% progress I stopped the installation and thought "this cannot be the right way".

```
$ yay -S kodi-addon-inputstream-adaptive-18-git
:: There are 3 providers available for kodi-bin:
:: Repository AUR
    1) kodi-bin-devel 2) kodi-gbm-devel 3) kodi-wayland-devel

Enter a number (default=1): 1
:: Checking for conflicts...
:: Checking for inner conflicts...

==> Package conflicts found:
 -> Installing kodi-devel will remove: kodi-rbp (kodi)

==> Conflicting packages will have to be confirmed manually

[Aur: 3]  kodi-devel-18.5pre16-1 (kodi-bin-devel kodi-devel)  kodi-addon-inputstream-adaptive-18-git-2.3.13.r3.gf782dcc-1
[Aur Make: 1]  kodi-devel-18.5pre16-1 (kodi-dev-devel)

```

> script.module.inputstreamhelper and inputstream.adaptive are different plugins, we need both. Our pvr.waipu grabs the stream and DRM License information from the waipu API. This informtion is passed to inputstream.adaptive which prepares the playback. The playback/decoding of DRM is handled by widevine. Widevine is not shipped with Kodi, it is a blob that has to be grabbed (due to the license) from google. That's what script.module.inputstreamhelper is for: It checks if widevine is available and downloads it for your platform.

Ah, this makes sense! I thought `script.module.inputstreamhelper` would download the License AND provide the functionality of `inputstream.adaptive`. Nevertheless, we still need to find a way to provide both of them in Arch ARM. There aren''t any intentions by Team Kodi on including inputstream in Kodi 19, are there?

Maybe we could grab the compiled binaries from LibreElec or OSMC for `inputstream.adaptive` and put them in a arm7h package. That way, neither us or the users of the package would have to compile `kodi-devel` on a rpi.

**Comment by c4tz** [comment]
Ok, so I went ahead and created some AUR packages:

https://aur.archlinux.org/packages/kodi-addon-inputstream-adaptive-any/
https://aur.archlinux.org/packages/kodi-addon-script-module-inputstreamhelper/
https://aur.archlinux.org/packages/kodi-addon-pvr-waipu/

The first one is just _yet another_ package which will install `inputstream.adaptive`, but doesn't depend on `kodi-devel`, so it can be used/compiled on a rpi.

The second installs `script.module.inputstreamhelper`, which (as I mentioned before) I couldn't find in the official Kodi repo on any of my devices. Its really just a dummy pkg copying the source into the right place and depends on `kodi-addon-inputstream-adaptive`, which is currently provided by 3 different packages, including the one above.

The third one is `pvr.waipu`, which in turn depends on the one above.

Everything takes about 10-15 mins to compile on my rpi, depending on the internet connection, because the Kodi source (about 49MB) has to be downloaded first in order to compile `inputstream.adaptive` and `pvr.waipu`.

What do you think about this? Any suggestions? :)

**Comment by flubshi** [comment]
I think `script.module.inputstreamhelper` is pretty hard to find within the official Kodi repo, but it is there.  It is added as dependency in pvr.waipu and you don't need to package `kodi-addon-script-module-inputstreamhelper`.

**Comment by c4tz** [comment]
Hmm, the problem is that even if it is added as a dependency for pvr.waipu, it doesn't get installed when I compile and `mv` pvr.waipu inside the AUR PKGBUILD. Is there a way to tell kodi directly to install it?

**Comment by flubshi** [comment]
Sorry for the late reply. I think you are right. The dependency (inputstreamhelper) is in kodi repository, but it is not resolved when moving the package. Unfortunately, I do not know if there is a cleaner way than shipping your additional package.
Anyway, thanks for maintaining the aur packages!

**Comment by c4tz** [comment]
> Unfortunately, I do not know if there is a cleaner way than shipping your additional package.

Yeah, even if one could somehow tell a Kodi instance to install a plugin via cli, there probably still were permission problems to overcome if Kodi runs in standalone mode as another user, e.g. As the problem of having multiple package managers on a system (for example with pip in python and pacman/apt-get or in this case with kodi) is usually solved by using the distro's package manager, I think this should be a good way to go down.

> Anyway, thanks for maintaining the aur packages!

No problem, I'll try my best to keep them in sync with your releases :)
