### ISSUE TITLE
Error when building for Leia

### ISSUE THREAD

**Issue by GitUser4711** [flubshi/pvr.waipu#38]
RPi4 with latest Debian (Raspbian) Buster. Followed the build instructions from Leia branch github page and included readme.md:

1. `git clone --branch Leia https://github.com/xbmc/xbmc.git`
2. `git clone --branch Leia https://github.com/flubshi/pvr.waipu.git`
3. `cd pvr.waipu && mkdir build && cd build`
4. `cmake -DADDONS_TO_BUILD=pvr.waipu -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons`
5. `make`

> -- No platform specific file _mypath_/xbmc/cmake/addons/depends/linux/CMakeLists.txt found
--
CMake Error at CMakeLists.txt:441 (message):
  pvr.waipu did not match any of the supported addons.  A list of supported
  addons can be viewed by building the 'supported_addons' target.  Addon
  definitions are loaded from ADDONS_DEFINITION_DIR
  (_mypath_/xbmc/cmake/addons/addons).

It seems pretty obvious that a folder with some info in it is expected for pvr.waipu - but not sure why we'd try to build an addon not in the (Leia) branch with a check against addons in that branch...

Am I missing something, or are unlisted steps required when building?

**Comment by flubshi** [comment]
I described the steps [on kodinerds](https://www.kodinerds.net/index.php/Thread/64613-Release-PVR-Plugin-Waipu-tv-f%C3%BCr-Kodi-18-19/?postID=547997#post547997l)

pvr.waipu is not an official Kodi plugin for Kodi Leia. Therefore, two files must be added within the cloned Kodi directory:

step 2.5.:
```
mkdir -p xbmc/cmake/addons/addons/pvr.waipu/
echo "pvr.waipu https://github.com/flubshi/pvr.waipu master" > xbmc/cmake/addons/addons/pvr.waipu/pvr.waipu.txt
echo "all" > xbmc/cmake/addons/addons/pvr.waipu/platforms.txt
```

**Comment by GitUser4711** [comment]
Thanks, that should exactly cover what was missing in the Leia specific instructions here on the project page.
