### ISSUE TITLE
Addon does not compile on Windows

### ISSUE THREAD

**Issue by ksooo** [flubshi/pvr.waipu#4]
```
[ 33%] Building CXX object CMakeFiles/pvr.waipu.dir/src/Utils.cpp.obj
Utils.cpp
D:\jenkins\workspace\binary-addons\kodi-windows-i686-Matrix\tools\depends\target\binary-addons\pvr.waipu\src\Utils.cpp(117): error C3861: 'strptime': identifier not found
NMAKE : fatal error U1077: 'C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe' : return code '0x2'
Stop.
```

'strptime' does not exit on Windows!

**Comment by ksooo** [comment]
Just copy the most recent code from pvr.zattoo and you should be done. ;-)

=> https://github.com/rbuehlma/pvr.zattoo/blob/Matrix/src/Utils.cpp#L109 ff.

**Comment by flubshi** [comment]
Thanks @ksooo for reporting this issue. Copying from pvr.zattoo is my normal workflow ;)

I also added appveyor to get notified about windows build issues.

**Comment by ksooo** [comment]
Now, that you are "official", please keep in mind:

* With every commit you merge/push you should bump the addon version to keep things unambiguous. Others will grab your stuff at every time (e.g. Milhouse builds, every day)
* If you want to release a new version of your addon (to the binary addon repo, for instance), please tag the respective commit, following the scheme major.minor.micro-branch (Exeample: 1.0.1-Matrix)
* major: new kodi version or major addon rewrite
* minor: new functionality
* micro: fixes only

**Comment by flubshi** [comment]
Okay, thanks for this information. Didn't know that I have to bump the version every commit.

Any preference regarding the major version number? e.g. keeping it synced with the kodi version 19.0.1-Matrix?

**Comment by ksooo** [comment]
Is just a number, imo no need to sync with Kodi version number.

**Comment by ksooo** [comment]
So, would you like to add the addon version bump for the windows build fix now? I really think you should do (quickly). And don't forget to tag if you want to see the new release in the binary addon repo.

**Comment by flubshi** [comment]
Done. From now I will use version 1.x.x-Matrix for all matrix versions of pvr.waipu.

**Comment by ksooo** [comment]
:+1:
