### ISSUE TITLE
Channels are listet but don't start

### ISSUE THREAD

**Issue by biker3107** [flubshi/pvr.waipu#55]
waipu Addon is correctly installed on an Android TV, EPG and Channels are actualized, but if you try to start a stream nothing happens. Sometimes the stream starts but mostly not ;(

**Comment by flubshi** [comment]
Thanks for reporting your issue. Please provide some additional information: Which Kodi version are you using? Which version of pvr.waipu and inputstream.adaptive are installed?
Is the plugin inputstream.adaptive enabled?

Is there a pattern which channels/streams are working? Is there a difference between public channels (ARD, ZDF) and non public (RTL, Pro7)?

**Comment by biker3107** [comment]
Kodi: v -18.5 leia; waipu pvr flubshi-0.2.1 inputStreamhelper (script.module.inputstreanhelper 0.4.1 (installed)  - cannot be desactivated - therefore its active. No difference between public and non public. Don't know why sometimes everything seems to run, but most times not. Today no chance, the play symbol disappear shortly after trying to start the stream and you can only see the EPG informations?? I installed KODI on my Windows 10 PC too, and its the same issue!

**Comment by flubshi** [comment]
Is inputstream.adaptive installed? (Addons -> Benutzer-Addons -> Videoplayer InputStream Addons -> InputStream Adaptive)

**Comment by biker3107** [comment]
das input stream adaptive war deaktiviert. Hoffentlich war das der Fehler und KODI funktioniert jetzt dauerhaft. Kann es sein, dass dieses addon sich hin und wieder beim Neustart von KODI deaktiviert? Vorerst ist das Problem gelöst - Dankeschön!!

**Comment by biker3107** [comment]
Sorry, but now it's the same problem again. input.stream.adaptive seems not to be the problem. Habe den waipu pvr client flubshi1.3.3 deintsalliert. Jetzt lässt er sich gar nicht mehr installieren. Nur die Abhängigkeiten können installiert werden

**Comment by flubshi** [comment]
Die Version 1.3.3 bzw. alle die mit einer 1.x.y beginnen sind für Kodi 19 - Matrix.
Für Kodi 18 - Leia musst Du die Versionen beginnend mit 0.x.y verwenden, z.B. 0.2.2.
Könnte das eventuell der Fehler sein? Oder welche Fehlermeldung siehst Du?

**Comment by biker3107** [comment]
Hab jetzt über VPN Zatoo getestet. Geht aber dieser Klient ist im vergleich zu dem waipu PVR ein Jammer. Musste mich etwas einarbeiten, da KODI sehr neu für mich ist. Hab jetzt nach langem probieren es geschafft die 0.2.1 Version über Zip Datei zu installieren und siehe da, alles läuft plötzlich wieder?! Keine Ahnung, wieso dieses Addon einmal läuft und dann wieder nicht. Eigentlich wäre es perfekt!

**Comment by biker3107** [comment]
sorrx
