### ISSUE TITLE
Add support for restarting Live TV

### ISSUE THREAD

**Issue by flubshi** [flubshi/pvr.waipu#58]
Waipu backend API provides a feature to restart a running live TV shows (playing for most channels). It would be great to include this feature in pvr.waipu.

Technically, an additional start time has to be set when retrieving information for setting StreamProperties.

**Comment by lenlennart** [comment]
Upvote :-) would love to see that feature soon

**Comment by flubshi** [comment]
Implemented in version 2.4.0-Matrix
