### ISSUE TITLE
Milhouse Libreelec builts are retired

### ISSUE THREAD

**Issue by AlbrechtL** [flubshi/pvr.waipu#89]
Thanks for your great plugin!

Unfortunately, Milhouse Libreelec builts are retired, see here: https://forum.kodi.tv/showthread.php?tid=358637

As an alternative test build can be used from here: https://test.libreelec.tv/

I hope for an updated plugin because of issue https://github.com/flubshi/pvr.waipu/issues/84.

**Comment by flubshi** [comment]
The updated pvr.waipu plugin will be included in a build of https://test.libreelec.tv/ after the following PR is merged:

https://github.com/LibreELEC/LibreELEC.tv/pull/4727

**Comment by AlbrechtL** [comment]
Thanks for replying. I'm looking forward to the new test build.

**Comment by AlbrechtL** [comment]
LibreELEC/LibreELEC.tv#4727 is merged now. But the waipu.tv PVR Client version is still 2.1.0.1.

I tried LibreELECT Git version b328711 on a Raspberry Pi 2
* https://github.com/LibreELEC/LibreELEC.tv/tree/b328711ce96050f19f1117fada892beb823dcf56
* RPi2 Image: https://test.libreelec.tv/LibreELEC-RPi2.arm-9.80-nightly-20201210-b328711.tar

**Comment by flubshi** [comment]
You need to download and install the addon in version 2.2.0.1 from: https://test.libreelec.tv/addons/9.80.8/

**Comment by AlbrechtL** [comment]
Thanks!

I downloaded https://test.libreelec.tv/addons/9.80.8/9.80.8-RPi2-arm-pvr.waipu-2.2.0.1.zip. First, I failed with installation before I managed to unzip it first. The install of pvr.waipu-2.2.0.1.zip was successfully.

Now the TV is working again but the following issues
* The scale is 4:3 instead of 16:9 which results in distortion
* Sound and video doesn't fit. I have a 10 s offset.

**Comment by flubshi** [comment]
> * The scale is 4:3 instead of 16:9 which results in distortion
> * Sound and video doesn't fit. I have a 10 s offset.

This is not related to the waipu plugins. It is either a Kodi, inputstream.adaptive or LibreELEC issue
